# Generated by Django 3.0.8 on 2020-12-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
        migrations.AddField(
            model_name='profiles',
            name='amount_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiles',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiles',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
